import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import Header from "@/components/layouts/Header";
import Sidebar from "@/components/layouts/Sidebar";

import "@/app/styles/globals.scss";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Board App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex flex-col w-full h-[calc(100vh-0px)] min-h-[calc(100vh-64px)] max-h-[calc(100vh-0px)] overflow-hidden">
          <Header />
          <div className="flex w-full h-[calc(100vh-0px)] min-h-[calc(100vh-64px)] max-h-[calc(100vh-0px)] pt-20">
            <div className="hidden md:flex w-[300px] shadow-lg">
              <Sidebar />
            </div>
            <div className="flex flex-col w-full h-full min-h-[calc(100vh-50px)] px-5 py-5 overflow-y-auto bg-tc_background_dark">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
